language: python
python:
- '2.7'
addons:
  sonarcloud:
    organization: "tier-one-monitoring"
services:
- postgresql
before_script:
- cp -f .travis/default.cfg test.cfg
- pip install pytest pytest-cov==2.6.0 python-coveralls mock coveralls
- pip install -r requirements.txt
- psql -c 'create database travis_test;' -U postgres
install:
- pip install -e .
script:
- coverage run --source=Monstr setup.py test
- coverage xml
- sonar-scanner
after_success:
- coveralls
notifications:
  email: false
