language: python
python:
  - "2.7"
services: 
  - postgresql
before_script:
  - cp -f .travis/default.cfg .
  - psql -c 'create database travis_test;' -U postgres
# command to install dependencies
install: "pip install -r requirements.txt"
#  # command to run tests
# script: nosetests
