language: python
python:
  - "2.7"
services: 
  - postgresql
before_script:
  - cp -f .travis/default.cfg test_conf.cfg
  - pip install pytest pytest-cov python-coveralls mock coveralls
  - pip install -r requirements.txt
  - psql -c 'create database travis_test;' -U postgres
# command to install dependencies
install: 
  - pip install -e .
# command to run tests
script: 
  - coverage run --source=Monstr setup.py test
after_success:
  - coveralls
notifications:
  email: false
