language: python
python:
  - "2.7"
services: 
  - postgresql
before_script:
  - cp -f .travis/default.cfg .
  - pip install python-coveralls
  - pip install pytest pytest-cov
  - pip install -r requirements.txt
  - pip install coveralls
  - psql -c 'create database travis_test;' -U postgres
# command to install dependencies
install: 
  - pip install -e .
# command to run tests
script: 
  - coverage run --source=Monstr setup.py test
after_success:
  - coveralls

